name: CI

on:
  pull_request: {}
  push:
    branches:
      - staging
      - trying
      - master

env:
  RUST_BACKTRACE: full

jobs:
  build:
    name: ${{ matrix.name }}
    needs: [style]

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name:
          - linux / stable
          - linux / beta

        include:
          - name: linux / stable
            os: ubuntu-latest
            rust: stable
          - name: linux / beta
            os: ubuntu-latest
            rust: beta

    steps:
      - name: Test_easy
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./LeetCode/Cargo.toml

      - name: Test_medium
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./LeetCode/Cargo.toml