name: CI

on:
  pull_request: {}
  push:
    branches:
      - staging
      - trying
      - master

env:
  RUST_BACKTRACE: full

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clean temp directory
        run: cat ./LeetCode/Easy/Cargo.toml

      - name: Test_easy
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./Easy/Cargo.toml

      - name: Test_medium
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./Medium/Cargo.toml